import type { AccountRole } from "@/lib/auth/roles";
import type { InteractiveMessagePayload } from "@/lib/whatsapp/interactive";

export type {
  InteractiveMessagePayload,
  InteractiveButtonsPayload,
  InteractiveListPayload,
  InteractiveButton,
  InteractiveListRow,
  InteractiveListSection,
} from "@/lib/whatsapp/interactive";

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
  /** Custom cargo (migration 058) — null if never assigned one. */
  role_id: string | null;
  sector_ids: string[];
}

// ---- Cargos, Permissões, Setores (migration 058) --------------------------

export type PlatformEnvironment = "comercial" | "operational";

/** One row of the global permissions catalog. */
export interface Permission {
  id: string;
  environment: PlatformEnvironment;
  module: string;
  action: string;
  label: string;
}

/** A custom cargo, with the ids of the permissions it grants. */
export interface Role {
  id: string;
  account_id: string;
  name: string;
  environments: PlatformEnvironment[];
  is_system_default: boolean;
  permission_ids: string[];
}

export interface Sector {
  id: string;
  account_id: string;
  name: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, "owner">;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  phone: string;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  name?: string;
  email?: string;
  company?: string;
  website?: string | null;
  instagram?: string | null;
  avatar_url?: string;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export type CustomFieldEntityType = "contact" | "deal";

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  /** Which entity this field applies to, added in migration 043. Defaults
   *  to 'contact' for every pre-043 row. */
  entity_type: CustomFieldEntityType;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

export interface DealCustomValue {
  id: string;
  deal_id: string;
  custom_field_id: string;
  value?: string | null;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  user_id: string;
  note_text: string;
  created_at: string;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

export interface Conversation {
  id: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  assigned_agent_id?: string;
  last_message_text?: string;
  last_message_at?: string;
  unread_count: number;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  /**
   * AI auto-reply state for this thread (migration 029 + 033):
   *  - `ai_autoreply_disabled` — the bot is paused here (a human took
   *    over, or the model handed off). Sticky until re-enabled.
   *  - `ai_reply_count` — how many times the bot has auto-replied,
   *    checked against the account's per-conversation cap.
   *  - `ai_handoff_summary` — short internal note the bot wrote when it
   *    handed off, shown to whoever takes the thread over.
   */
  ai_autoreply_disabled?: boolean;
  ai_reply_count?: number;
  ai_handoff_summary?: string | null;
}

// ============================================================
// Notifications (migration 027)
// ============================================================

export type NotificationType = 'conversation_assigned' | 'contract_signed';

export interface Notification {
  id: string;
  account_id: string;
  /** Recipient — the agent this notification is for. */
  user_id: string;
  type: NotificationType;
  conversation_id?: string;
  contact_id?: string;
  /** Set for `contract_signed` (migration 054). */
  deal_id?: string;
  contract_id?: string;
  /** Who triggered it. Null when an automation/system assigned it. */
  actor_user_id?: string;
  title: string;
  body?: string;
  read_at?: string;
  created_at: string;
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive';
export type MessageStatus = 'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  /**
   * MIME type of `media_url`'s content, as Meta reported it. Inbound
   * media only — outbound URLs already carry a filename and extension.
   * Null on every row written before migration 039.
   */
  media_type?: string | null;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Structured payload of an OUTBOUND interactive message (reply
   * buttons or list) we sent. Lets the thread re-render the buttons /
   * rows, not just the body text. Only set when `content_type ===
   * 'interactive'` and `sender_type` is agent/bot. Migration 035.
   */
  interactive_payload?: InteractiveMessagePayload;
  /**
   * True when the AI auto-reply bot generated + sent this message (as
   * opposed to a human agent or a deterministic Flow/automation send,
   * which all share `sender_type='bot'`/`'agent'`). Drives the "AI"
   * badge in the inbox. Migration 033.
   */
  ai_generated?: boolean;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  phone_number_id: string;
  waba_id?: string;
  access_token: string;
  verify_token?: string;
  status: 'connected' | 'disconnected';
  connected_at?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. */
  last_registration_error?: string;
  /**
   * When true (the default), the inbound webhook copies received media
   * into the `chat-media` bucket so attachments outlive Meta's ~30-day
   * retention. Turning it off keeps storage flat and accepts that
   * inbound attachments expire. Migration 039.
   */
  mirror_inbound_media?: boolean;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  created_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  /**
   * 'contract_closed' marks the single, automatically-created stage every
   * pipeline gets (see migration 054) — a signed contract moves the deal
   * here automatically. Locked in the Pipeline settings UI: no rename,
   * recolor, reorder, or delete.
   */
  kind: "custom" | "contract_closed";
  created_at: string;
}

export type DealStatus = 'open' | 'won' | 'lost';

export type DealLineItemType = 'mensal' | 'pontual';

export interface DealLineItem {
  id: string;
  deal_id: string;
  account_id: string;
  type: DealLineItemType;
  label?: string | null;
  value: number;
  created_at: string;
}

export interface DealTag {
  id: string;
  deal_id: string;
  account_id: string;
  label: string;
  color: string;
  created_at: string;
}

/** One stage transition for a deal (migration 057). `from_stage_id` is null
 *  for the row seeded at pipeline entry (backfilled or on creation). */
export interface DealStageHistoryRow {
  id: string;
  deal_id: string;
  account_id: string;
  from_stage_id: string | null;
  to_stage_id: string;
  changed_at: string;
}

/** A commercial goal for one calendar month (migration 057). `period_month`
 *  is always the first day of the month. */
export interface DealGoal {
  id: string;
  account_id: string;
  period_month: string;
  amount: number;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
}

/** One row from the `search_deals` RPC (migration 055) — backs the
 *  Pipelines page's cross-pipeline deal search. */
export interface DealSearchResult {
  deal_id: string;
  title: string;
  pipeline_id: string;
  pipeline_name: string;
  stage_id: string;
  stage_name: string;
  contact_name: string | null;
  contact_company: string | null;
  assignee_name: string | null;
  matched_snippet: string | null;
  rank: number;
  total_count: number;
}

// ---- Contrato (migration 052-054) --------------------------------------

export interface ContractTemplate {
  id: string;
  account_id: string;
  name: string;
  /** Plain text/paragraphs with {{variable}} placeholders — see CONTRACT_TEMPLATE_VARIABLES. */
  content: string;
  is_active: boolean;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
}

export type ContractSigningMethod = 'clicksign' | 'virtual';
export type ContractStatus =
  | 'draft'
  | 'sent'
  | 'viewed'
  | 'signed'
  | 'declined'
  | 'expired'
  | 'cancelled';

export interface DealContract {
  id: string;
  account_id: string;
  deal_id: string;
  template_id?: string | null;
  razao_social: string;
  cnpj: string;
  endereco: string;
  nome_representante: string;
  cpf_representante: string;
  client_email: string;
  rendered_content?: string | null;
  signing_method: ContractSigningMethod;
  status: ContractStatus;
  clicksign_envelope_id?: string | null;
  clicksign_document_id?: string | null;
  clicksign_signer_id?: string | null;
  clicksign_sign_url?: string | null;
  signed_pdf_path?: string | null;
  token_hash?: string | null;
  signed_at?: string | null;
  signed_ip?: string | null;
  signed_user_agent?: string | null;
  created_by?: string | null;
  sent_at?: string | null;
  expires_at?: string | null;
  created_at: string;
  updated_at: string;
}

export type DealContractEventType =
  | 'created'
  | 'sent'
  | 'viewed'
  | 'signed'
  | 'declined'
  | 'expired'
  | 'cancelled'
  | 'webhook_received';

export interface DealContractEvent {
  id: string;
  contract_id: string;
  account_id: string;
  event_type: DealContractEventType;
  actor_user_id?: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
}

export interface DealActivity {
  id: string;
  deal_id: string;
  account_id: string;
  user_id?: string | null;
  type: string;
  title: string;
  detail?: string | null;
  created_at: string;
}

export interface DealComment {
  id: string;
  deal_id: string;
  account_id: string;
  user_id?: string | null;
  body: string;
  created_at: string;
  /** Hydrated by the detail page so the comment list can show an author name. */
  author?: Profile;
}

export interface DealNextStep {
  id: string;
  deal_id: string;
  account_id: string;
  title: string;
  done: boolean;
  due_date?: string | null;
  position: number;
  created_at: string;
}

export interface ServiceCatalogItem {
  id: string;
  account_id: string;
  name: string;
  type: DealLineItemType;
  default_value: number;
  created_at: string;
}

export interface Deal {
  id: string;
  user_id: string;
  pipeline_id: string;
  stage_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  conversation_id?: string;
  assigned_to?: string | null;
  title: string;
  value: number;
  currency?: string;
  notes?: string;
  expected_close_date?: string;
  status?: DealStatus;
  created_at: string;
  updated_at?: string;
  /** Set by a DB trigger the instant status flips to won/lost (migration 040);
   *  cleared back to null if the deal is reopened. Null while status is 'open'. */
  closed_at?: string | null;
  /** Free-text segment ("ex: Estética"), added in migration 041. */
  segment?: string | null;
  /** Free-text region ("Cidade, UF"), added in migration 041. */
  region?: string | null;
  frente_leadgen?: boolean;
  frente_avr?: boolean;
  media_investment?: number | null;
  proposal_url?: string | null;
  /** Free-text/select reason captured when the deal is marked Lost (migration 043). */
  lost_reason?: string | null;
  /** Optional observation attached to a loss, independent of `lost_reason` (migration 056). */
  lost_reason_note?: string | null;
  /** Structured acquisition-channel key, or free text when "Outro" was picked (migration 056). */
  origin?: string | null;
  /** Set when this deal was created by importing a Prospecção candidate (migration 049). */
  prospecting_candidate_id?: string | null;
  /** Last real commercial activity (stage change, activity log, comment, next
   *  step created/completed) — distinct from `updated_at`, which bumps on
   *  any edit (migration 057). */
  last_activity_at: string;
  contact?: Contact;
  stage?: PipelineStage;
  assignee?: Profile;
  /** Who created the deal — joined in for the dashboard's user filter. */
  creator?: Profile;
  /** Batch-hydrated by loadPipelineDeals/loadDealById — the deal's mensal/pontual entries. */
  lineItems?: DealLineItem[];
  /** Batch-hydrated by loadPipelineDeals/loadDealById — per-deal colored tags. */
  dealTags?: DealTag[];
}

export type BroadcastStatus = 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
export type RecipientStatus = 'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  template_name: string;
  template_language: string;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  /**
   * Set while a server-side delivery pass is fanning out, NULL when
   * idle. Claimed with a conditional UPDATE so two resumes can't both
   * send. Added in migration 038.
   */
  delivery_locked_at?: string | null;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  /**
   * Positional body values for this recipient's template send
   * ({{1}}, {{2}}, …), frozen when the broadcast was planned so a
   * server-side resume reproduces the original pass exactly.
   * Added in migration 038; null on rows created before it.
   */
  template_params?: string[] | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based'
  /** Customer tapped a reply button / list row whose id matches; lets
   *  multi-step menus be chained across automations. */
  | 'interactive_reply';

export type AutomationStepType =
  | 'send_message'
  | 'send_buttons'
  | 'send_list'
  | 'send_template'
  | 'add_tag'
  | 'remove_tag'
  | 'assign_conversation'
  | 'update_contact_field'
  | 'create_deal'
  | 'wait'
  | 'condition'
  | 'send_webhook'
  | 'close_conversation';

export type AutomationLogStatus = 'success' | 'partial' | 'failed';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  /**
   * `contains` (the default) is a raw substring test, so a short keyword
   * matches inside longer words — "k" fires on "thanks". `word` is the
   * boundary-aware alternative added for issue #409; see
   * `matchesWholeWord` in `@/lib/automations/engine` for its exact
   * semantics. Flows carry their own keyword config and stay
   * substring-only (`@/lib/flows/types`).
   */
  match_type: 'exact' | 'contains' | 'word';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export interface InteractiveReplyTriggerConfig {
  /** Button / list-row ids to match, exact. Any one matching fires. */
  reply_ids: string[];
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | InteractiveReplyTriggerConfig
  | Record<string, unknown>;

export interface SendMessageStepConfig {
  text: string;
}

/**
 * `send_buttons` / `send_list` step configs carry the full interactive
 * payload (same shape stored on messages + quick replies). `kind` is
 * implied by the step_type but kept on the payload for a uniform shape.
 */
export type SendButtonsStepConfig = InteractiveMessagePayload;
export type SendListStepConfig = InteractiveMessagePayload;

export interface SendTemplateStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  mode: 'specific' | 'round_robin';
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
}

export type ConditionSubject =
  | 'contact_field'
  | 'tag_presence'
  | 'message_content'
  | 'time_of_day';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendButtonsStepConfig
  | SendListStepConfig
  | SendTemplateStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Quick replies — reusable snippets (migration 035)
// ============================================================

export type QuickReplyKind = 'text' | 'interactive';

export interface QuickReply {
  id: string;
  /** Account tenancy key — shared across all members of the account. */
  account_id: string;
  /** Author / audit only. */
  user_id: string;
  title: string;
  kind: QuickReplyKind;
  /** Set when `kind === 'text'`. */
  content_text?: string | null;
  /** Set when `kind === 'interactive'`. */
  interactive_payload?: InteractiveMessagePayload | null;
  created_at: string;
  updated_at: string;
}

// ============================================================
// Gestão de Tarefas — Quadros/Kanban/Tarefas (Etapa 2, migration 060)
// Mirrors Pipeline/PipelineStage/Deal's shape 1:1 (Board≈Pipeline,
// BoardStage≈PipelineStage, Task≈Deal).
// ============================================================

export interface Board {
  id: string;
  account_id: string;
  name: string;
  description?: string | null;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
}

export interface BoardStage {
  id: string;
  board_id: string;
  name: string;
  position: number;
  color?: string | null;
  created_at: string;
}

export type TaskPriority = 'low' | 'medium' | 'high';
export type TaskStatus = 'open' | 'done';

export interface Task {
  id: string;
  account_id: string;
  board_id: string;
  stage_id: string;
  parent_task_id?: string | null;
  title: string;
  contact_id?: string | null;
  sector_id?: string | null;
  assignee_id?: string | null;
  priority: TaskPriority;
  is_urgent: boolean;
  /** Tiptap JSON document — see src/lib/tasks/briefing.ts. */
  briefing?: Record<string, unknown> | null;
  position: number;
  status: TaskStatus;
  start_date?: string | null;
  due_date?: string | null;
  estimated_minutes?: number | null;
  created_by?: string | null;
  completed_at?: string | null;
  recurrence_rule_id?: string | null;
  /** Link to a shared Google Drive folder the team already has access to
   *  (Etapa 2, Fase 6) -- just a URL, no Drive API integration. */
  drive_folder_url?: string | null;
  created_at: string;
  updated_at: string;
  /** Hydrated client-side, not selected from `tasks` directly. */
  assignee?: Profile | null;
  contact?: Contact | null;
  sector?: Sector | null;
  tags?: TaskTag[];
  subtask_count?: number;
}

export type TaskRecurrenceRuleType = 'weekly' | 'monthly_day' | 'monthly_first_business_day';

export interface TaskRecurrenceRule {
  id: string;
  account_id: string;
  template_task_id: string;
  rule_type: TaskRecurrenceRuleType;
  /** 0 = Sunday .. 6 = Saturday. Only set (and meaningful) for "weekly". */
  weekday?: number | null;
  /** 1..31. Only set (and meaningful) for "monthly_day". */
  day_of_month?: number | null;
  next_run_at: string;
  active: boolean;
  created_by?: string | null;
  created_at: string;
}

export interface TaskTag {
  id: string;
  task_id: string;
  account_id: string;
  label: string;
  color: string;
  created_at: string;
}

export interface TaskChecklistItem {
  id: string;
  task_id: string;
  account_id: string;
  label: string;
  done: boolean;
  position: number;
  created_at: string;
}

export interface TaskComment {
  id: string;
  task_id: string;
  account_id: string;
  user_id?: string | null;
  body: string;
  parent_comment_id?: string | null;
  created_at: string;
  author?: Profile;
}

export interface TimesheetEntry {
  id: string;
  account_id: string;
  task_id: string;
  user_id?: string | null;
  started_at: string;
  ended_at?: string | null;
  is_manual: boolean;
  description?: string | null;
  created_at: string;
  /** Hydrated client-side. */
  author?: Profile;
  /** Hydrated only for the account-wide "active timer" lookup (Header). */
  task?: Pick<Task, "id" | "title" | "board_id">;
}

export interface TaskStageHistory {
  id: string;
  task_id: string;
  account_id: string;
  from_stage_id?: string | null;
  to_stage_id: string;
  changed_at: string;
}

export interface TaskActivity {
  id: string;
  task_id: string;
  account_id: string;
  user_id?: string | null;
  type: string;
  title: string;
  detail?: string | null;
  created_at: string;
  author?: Profile;
}
